# Reload config
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-g
set -g base-index 1
setw -g pane-base-index 1

set -g automatic-rename off
set -g allow-passthrough on
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",-256color:Tc"

set -g aggressive-resize on
set-hook -g client-attached 'resize-window -A'
