# Switch key tables
bind w switch-client -T window
bind p switch-client -T panel
bind s switch-client -T session

# ---------------- SESSION TABLE ----------------
bind -T session n command-prompt -p "New session name:" "new-session -s '%%'" \; switch-client -T prefix
bind -T session r command-prompt -I "#S" "rename-session '%%'" \; switch-client -T prefix
bind -T session l display-popup -E "tmux choose-session" \; switch-client -T prefix
bind -T session x kill-session \; switch-client -T prefix

# ---------------- WINDOW TABLE ----------------
bind -T window n new-window \; switch-client -T prefix
bind -T window r command-prompt -I "#W" "rename-window '%%'" \; switch-client -T prefix
bind -T window l choose-window \; switch-client -T prefix
bind -T window x kill-window \; switch-client -T prefix
bind -T window m switch-client -T move-window
bind -T window q switch-client -T prefix

# Move window table
bind -T move-window h swap-window -t -1
bind -T move-window l swap-window -t +1
bind -T move-window q switch-client -T prefix

# ---------------- PANEL TABLE ----------------
bind -T panel n split-window -h \; switch-client -T prefix
bind -T panel v split-window -h \; switch-client -T prefix
bind -T panel h split-window -v \; switch-client -T prefix
bind -T panel m switch-client -T move-pane
bind -T panel x kill-pane \; switch-client -T prefix

# Move pane table
bind -T move-pane h swap-pane -L
bind -T move-pane l swap-pane -R
bind -T move-pane k swap-pane -U
bind -T move-pane j swap-pane -D
bind -T move-pane q switch-client -T prefix
