default:
  just -g --list

[group('hyprland')]
hypr-reload:
  hyprctl reload

[group('ssh')]
keygen email:
  ssh-keygen -t rsa -C {{email}}



install_cmd := if os() =~ 'linux' {
  'sudo pacman -S --noconfirm'
} else if os() =~ 'macos' {
  'brew install'
}

[group('pacman')]
install +args:
  {{install_cmd}} {{args}}
