default:
  just -g --list

[group('hyprland')]
hypr-reload:
  hyprctl reload

[group('ssh')]
keygen email:
  ssh-keygen -t rsa -C {{email}}

[group('brew')]
[group('pacman')]
install +args:
  {{\
    if os() =~ 'linux' { \
      'sudo pacman -S --noconfirm' \
    } else if os() =~ 'macos' { \
      'brew install' \
    } else { \
      error('unsupported OS') \
    } \
  }} {{args}}
