# Restore Key Stroke
RestoreKeyStroke=
# Input Method
InputMethod=VNI
# Output Charset
OutputCharset=Unicode
# Enable spell check
SpellCheck=False
# Enable Macro
Macro=False
# Capitalize Macro
CapitalizeMacro=False
# Auto restore keys with invalid words
AutoNonVnRestore=False
# Use oà, _uý (instead of òa, úy)
ModernStyle=True
# Allow type with more freedom
FreeMarking=False
# Underline the preedit text
DisplayUnderline=False

