accordion-padding = 30
after-startup-command = ["exec-and-forget /etc/profiles/per-user/dev/bin/kitty"]
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
exec-on-workspace-change = []
on-focus-changed = []
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
start-at-login = true

[key-mapping]
preset = "qwerty"

[mode.main.binding]
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"
alt-a = "workspace A"
alt-b = "workspace B"
alt-c = "workspace C"
alt-d = "workspace D"
alt-e = "workspace E"
alt-f = "workspace F"
alt-g = "workspace G"
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-m = "workspace M"
alt-n = "workspace N"
alt-p = "workspace P"
alt-q = "workspace Q"
alt-r = "workspace R"
alt-s = "workspace S"
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-7 = "move-node-to-workspace 7"
alt-shift-8 = "move-node-to-workspace 8"
alt-shift-9 = "move-node-to-workspace 9"
alt-shift-a = "move-node-to-workspace A"
alt-shift-b = "move-node-to-workspace B"
alt-shift-c = "move-node-to-workspace C"
alt-shift-d = "move-node-to-workspace D"
alt-shift-e = "move-node-to-workspace E"
alt-shift-f = "move-node-to-workspace F"
alt-shift-g = "move-node-to-workspace G"
alt-shift-h = "move left"
alt-shift-i = "move-node-to-workspace I"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-shift-m = "move-node-to-workspace M"
alt-shift-n = "move-node-to-workspace N"
alt-shift-o = "move-node-to-workspace O"
alt-shift-p = "move-node-to-workspace P"
alt-shift-q = "move-node-to-workspace Q"
alt-shift-r = "move-node-to-workspace R"
alt-shift-s = "move-node-to-workspace S"
alt-shift-t = "move-node-to-workspace T"
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-shift-u = "move-node-to-workspace U"
alt-shift-v = "move-node-to-workspace V"
alt-shift-w = "move-node-to-workspace W"
alt-shift-x = "move-node-to-workspace X"
alt-shift-y = "move-node-to-workspace Y"
alt-shift-z = "move-node-to-workspace Z"
alt-t = "workspace T"
alt-tab = "workspace-back-and-forth"
alt-u = "workspace U"
alt-v = "workspace V"
alt-w = "workspace W"
alt-x = "workspace X"
alt-y = "workspace Y"
alt-z = "workspace Z"
cmd-alt-h = []

[[on-window-detected]]
run = ["move-node-to-workspace 1"]

[on-window-detected.if]
app-id = "net.kovidgoyal.kitty"

[[on-window-detected]]
run = ["move-node-to-workspace 2"]

[on-window-detected.if]
app-id = "org.mozilla.firefox"

[[on-window-detected]]
run = ["move-node-to-workspace 3"]

[on-window-detected.if]
app-id = "Mattermost.Desktop"

[[on-window-detected]]
run = ["move-node-to-workspace C"]

[on-window-detected.if]
app-id = "com.google.Chrome"

[[on-window-detected]]
run = ["move-node-to-workspace D"]

[on-window-detected.if]
app-id = "com.electron.dockerdesktop"

[[on-window-detected]]
run = ["move-node-to-workspace S"]

[on-window-detected.if]
app-id = "com.spotify.client"

[[on-window-detected]]
run = ["move-node-to-workspace G"]

[on-window-detected.if]
app-id = "com.openai.chat"

[[on-window-detected]]
run = ["move-node-to-workspace Y"]

[on-window-detected.if]
app-id = "app.yaak.desktop"

[[on-window-detected]]
run = ["move-node-to-workspace 9"]

[on-window-detected.if]
app-id = "app.zen-browser.zen"

[[on-window-detected]]
run = ["move-node-to-workspace 9"]

[on-window-detected.if]
app-id = "app.cattr"

[[on-window-detected]]
run = ["move-node-to-workspace T"]

[on-window-detected.if]
app-id = "com.atlassian.trello"

[[on-window-detected]]
run = ["move-node-to-workspace B"]

[on-window-detected.if]
app-id = "com.bitwarden.desktop"
