config-file := "~/.config/nixos-config"

default:
  @just --list --justfile {{justfile()}}

git-add:
  git add .
update:
  nix flake update
  @just build
build:
  @just git-add
  nix run .#build-switch
update-home-manager:
  nix flake update home-manager

edit-secrets:
  sops ~/.config/nix-darwin/serects/secrets.yaml
